### ISSUE TITLE
Add the ability to include markdown from a separate file. 

### ISSUE THREAD

**Issue by zephraph** [zephraph/nunjucks-markdown#2]
Should be able to include markdown files.

```
{% markdown "content.md" %}
```

As suggested by @tedw

**Comment by zephraph** [comment]
Okay, so I just added a test in to verify, but adding and include tag inside the markdown tag now works. I still fully intent to add argument support but I need to figure out where the relative path variable is saved. I should have that tonight or tomorrow if all goes well. 

Again, sorry for being absent guys! Hope the update works well for you, if you have any issues let me know.

**Comment by zephraph** [comment]
The implementation was easier than expected. 

Includes can be done with ```{% markdown "content.md" %}``` and it will respect nunjuck's configured relative path.

**Comment by tedw** [comment]
Happy New Year! Thanks for making the update. I just tested it out, but it's still looking in the root directory. I'm using 'gulp-nunjucks-render' instead of 'nunjucks' which might have something to do with it.

**Comment by zephraph** [comment]
Strange. If you have time could you try to write a test that replicates your failure? If not I can try to do it soon, but it'll probably be next week at the earliest because I'm slammed at work right now.

**Comment by zephraph** [comment]
I'm going to close this again and open up a new issue for this problem.

**Comment by tedw** [comment]
So sorry for not getting back to you sooner! Work got very busy for me and I lost track of this.

I was finally able to test again and can confirm the issue has been resolved! I think the issue I had previously was because I was using an older syntax for 'marked' settings. Once I switched to the marked.setOptions() method everything worked great.

**Comment by zephraph** [comment]
Good! I'm glad it works for you.

I updated it again after that. The latest version doesn't even require marked. You just provide your own rendering function.
