### ISSUE TITLE
Refactor markdown tag to enable inner templates

### ISSUE THREAD

**Issue by zephraph** [zephraph/nunjucks-markdown#3]
Currently when markdown text is rendered in a tag it's treated like raw data. I'd like to refactor the parser so it handles internal tags. 

It'll allow for using templates within markdown as follows:

```
{% markdown %}{% include "content/readme.md" %}{% endmarkdown %}
```

**Comment by zephraph** [comment]
Should work as of v0.6.0

**Comment by ivan-kleshnin** [comment]
Wow, great! :thumbsup: I'll check it out as soon as possible. Keep up!
